# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  qc_style:
    repos:
      obsea-drift-monitor:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      obsea-drift-monitor:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      obsea-drift-monitor:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  GIT_COMMITTER_NAME: "Borja Esteban Sanchis"
  GIT_COMMITTER_EMAIL: "boressan@outlook.com"
  LANG: C.UTF-8

timeout: 600
